name: Fucking Swift Concurrency

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: fuckingswiftconcurrency-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: 1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Mise dependencies
        uses: jdx/mise-action@v2

      - name: Install project dependencies
        run: mise run install

      - name: Build
        run: mise run build
